### ISSUE TITLE
Latest update causes macro bar sides to expand, and has issue with Custom Hotbar

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#12]
Just updated to the latest version, and the two little bars (the one with the folder and the one with the arrows that lets you scroll through the 5 hotbar rows) on either side of the main hotbar have expanded downward, so that they touch the bottom of the screen, while the hotbar itself remains a bit above it. Not a huge deal, but seems unintentional so I thought I mentioned it.

Inexplicably, this latest update (the previous version didn't have this problem) causes the Custom Hotbar mod's hotbar to be placed about 1 hotbar's worth of height above its original position, and even though there are configuration options for the Custom Hotbar mod, they won't obey me while your mod is installed.

**Comment by GambetTV** [comment]
Just in case some images help illustrate the problem. First is with your mod uninstalled, second is with it installed.

![Test1](https://user-images.githubusercontent.com/72000497/112591848-5cd8d300-8ddb-11eb-9b2b-ece7191bbea3.jpg)
![Test2](https://user-images.githubusercontent.com/72000497/112591858-5ea29680-8ddb-11eb-9c1e-2f79f47267cc.jpg)

**Comment by saif-ellafi** [comment]
Thanks,
It will be a bit complicated to friend these two modules. Particularly because many stiles in Custom Hotbar module are "hardcoded" in the HTML elements themselves, rather than following style parametrization (imho not a good practice, but sometimes I understand it is convenient and fast).

I'll see what I can do to make this work right with Custom Hotbar, but any solution will have some "fixed solution" that will probably override some customizations in favour of stability.

**Comment by saif-ellafi** [comment]
Hi @GambetTV I have done some work on this, could you please check release 0.3.6 ? Thanks

**Comment by GambetTV** [comment]
Looks perfect! Thanks so much!
