### ISSUE TITLE
BUG: Hotbar & player list positions too high

### ISSUE THREAD

**Issue by GambetTV** [saif-ellafi/foundryvtt-minimal-ui#68]
For some reason the positions of the macro hotbar and player list has been raised several pixels from the default, and there doesn't seem to be a way to move it back down.

**Comment by saif-ellafi** [comment]
Hey @GambetTV Thanks! - Could you please check the recently released 1.3.0 build?? Assuming you are on V9. I patched that up before checking this issue.

**Comment by Tobyn52** [comment]
Hello.  I've done a bunch of testing, and it seems the culprit is Custom Hotbar. I tested the following combinations:

**1. Minimal UI, Monk's Hotbar, Custom Hotbar**
Core hotbar ends up positioned higher and the to right. Minimal's hotbar repostioning doesn't work. Custom's hotbar repositioning doesn't work.

**2. Minimal UI, Custom Hotbar**
Core hotbar ends up positioned slightly higher. Minimal's hotbar repositioning doesn't work. Custom's hotbar repositioning doesn't work.

**3. Monk's Hotbar, Custom Hotbar**
Core hotbar ends up in same position as #1.  Custom's hotbar repositioning doesn't work.

**4. Minimal UI, Monk's Hotbar**
Everything works.

Not sure how helpful this is, but I figured I'd share my findings.

**Comment by saif-ellafi** [comment]
Hey @Tobyn52 - your conclusions are correct. Custom Hotbar is enforcing positioning on the core Hotbar. However on today's release I have provided a workaround. Ideally, the change should be on custom Hotbar but at least for now we can survive this way.

Let me know if the latest version works fine.

**Comment by Farmeroz** [comment]
This latest version is causing a problem now. The main hotbar now "mirror" up the top of the screen (FVTT 0.8.9) and it "flickers" when hovering over it and you can't see any tool tips etc.  Reverted to previous version and everything works as expected.

**Comment by saif-ellafi** [comment]
Hmm what happened @Farmeroz - is this compatibility issue? Which version are you on?

**Comment by Farmeroz** [comment]
@saif-ellafi on FVTT 0.8.9 using Minimal UI 1.1.1.0 there is a glitch as follows:

![image](https://user-images.githubusercontent.com/89975749/147846874-e15b4dbc-39eb-4eda-b0b8-632c96c67e7f.png)

Main hot bar at bottom "flickers" and appears at the top of the page (and any mouseover/tool-tip appears on the top one.

![image](https://user-images.githubusercontent.com/89975749/147846901-57ecaf4a-6e0b-43cb-954e-3827ae75de4e.png)

I have to show you two images because it flickers and you can't screen capture it with both showing at once, but that's what happens.

With FVTT V9, that doesn't happen, but the left side bar is no longer "minimal":

![image](https://user-images.githubusercontent.com/89975749/147846946-516a34e9-5913-46bf-8bf3-425bbcae134e.png)

This is not a problem with FVTT 0.8.9

Both issues are not present in FVTT 0.8.9 or V9 when using Minimal UI 1.1.9

**Comment by saif-ellafi** [comment]
Thanks, but there must be a confusion. V9 does not wok with 1.1.9, Foundry V9 works with 1.2.0 or higher. Will take a look what is the issue here.

**Comment by Farmeroz** [comment]
> Thanks, but there must be a confusion. V9 does not wok with 1.1.9, Foundry V9 works with 1.2.0 or higher. Will take a look what is the issue here.

Thanks. It's weird!

**Comment by saif-ellafi** [comment]
@Farmeroz the last image you posted happens when you use Minimal UI 1.1.X with Foundry V9.

For V9 you should use Minimal UI 1.4.1 which is the latest version.

**Comment by saif-ellafi** [comment]
Yes confirmed 1.1.10 is broken with Custom Hotbar... I guess this is why I didn't want to support multiple versions of Minimal UI :( will see to fix it

**Comment by Farmeroz** [comment]
Thank you.  I think support for 0.8.9 only needs to be for a little while until everyone can move to V9 when all other modules are available.

However, on The Forge, the latest version available is 1.1.1.0 it seems?

![image](https://user-images.githubusercontent.com/89975749/147847567-e0813a18-d05f-4400-a90e-8daeb5780e2f.png)

**Comment by saif-ellafi** [comment]
Yes, 1.1.10 is the last version for Foundry 0.8.9 , while 1.4.1 is the last version for V9
I am not sure how the Forge works with multiple version builds!

BTW: I found the issue you mentioned above - I have fixed it without a new release (I had forgotten a line of code). If you uninstall 1.1.10 and reinstall it again, it should now work!

You can use this Manifest: https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/download/1.1.10/module.json

**Comment by Farmeroz** [comment]
Thanks, 1.1.10 from https://github.com/saif-ellafi/foundryvtt-minimal-ui/releases/download/1.1.10/module.json works perfectly in 0.8.9
